# Generated by Django 3.2.18 on 2023-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='movies/defaultMovieIMG.jpg', upload_to='movies/'),
        ),
    ]
